// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: slowquery.proto

package slowquery

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SlowLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RawLine       string                 `protobuf:"bytes,2,opt,name=raw_line,json=rawLine,proto3" json:"raw_line,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	QueryTime     float64                `protobuf:"fixed64,4,opt,name=query_time,json=queryTime,proto3" json:"query_time,omitempty"`
	LockTime      float64                `protobuf:"fixed64,5,opt,name=lock_time,json=lockTime,proto3" json:"lock_time,omitempty"`
	RowsSent      int64                  `protobuf:"varint,6,opt,name=rows_sent,json=rowsSent,proto3" json:"rows_sent,omitempty"`
	RowsExamined  int64                  `protobuf:"varint,7,opt,name=rows_examined,json=rowsExamined,proto3" json:"rows_examined,omitempty"`
	Sql           string                 `protobuf:"bytes,8,opt,name=sql,proto3" json:"sql,omitempty"`
	Database      string                 `protobuf:"bytes,9,opt,name=database,proto3" json:"database,omitempty"`
	Uuid          string                 `protobuf:"bytes,10,opt,name=uuid,proto3" json:"uuid,omitempty"`
	LogOffset     int64                  `protobuf:"varint,11,opt,name=log_offset,json=logOffset,proto3" json:"log_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlowLogEntry) Reset() {
	*x = SlowLogEntry{}
	mi := &file_slowquery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlowLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlowLogEntry) ProtoMessage() {}

func (x *SlowLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_slowquery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlowLogEntry.ProtoReflect.Descriptor instead.
func (*SlowLogEntry) Descriptor() ([]byte, []int) {
	return file_slowquery_proto_rawDescGZIP(), []int{0}
}

func (x *SlowLogEntry) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SlowLogEntry) GetRawLine() string {
	if x != nil {
		return x.RawLine
	}
	return ""
}

func (x *SlowLogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *SlowLogEntry) GetQueryTime() float64 {
	if x != nil {
		return x.QueryTime
	}
	return 0
}

func (x *SlowLogEntry) GetLockTime() float64 {
	if x != nil {
		return x.LockTime
	}
	return 0
}

func (x *SlowLogEntry) GetRowsSent() int64 {
	if x != nil {
		return x.RowsSent
	}
	return 0
}

func (x *SlowLogEntry) GetRowsExamined() int64 {
	if x != nil {
		return x.RowsExamined
	}
	return 0
}

func (x *SlowLogEntry) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *SlowLogEntry) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *SlowLogEntry) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SlowLogEntry) GetLogOffset() int64 {
	if x != nil {
		return x.LogOffset
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Sequence      int32                  `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Uuid          string                 `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	LogOffset     int64                  `protobuf:"varint,5,opt,name=log_offset,json=logOffset,proto3" json:"log_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_slowquery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_slowquery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_slowquery_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Ack) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Ack) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Ack) GetLogOffset() int64 {
	if x != nil {
		return x.LogOffset
	}
	return 0
}

type HeatQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     string                 `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	TopN          int32                  `protobuf:"varint,3,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeatQueryRequest) Reset() {
	*x = HeatQueryRequest{}
	mi := &file_slowquery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeatQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeatQueryRequest) ProtoMessage() {}

func (x *HeatQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slowquery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeatQueryRequest.ProtoReflect.Descriptor instead.
func (*HeatQueryRequest) Descriptor() ([]byte, []int) {
	return file_slowquery_proto_rawDescGZIP(), []int{2}
}

func (x *HeatQueryRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *HeatQueryRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *HeatQueryRequest) GetTopN() int32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

type TableHeat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TableName      string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	HeatScore      float64                `protobuf:"fixed64,2,opt,name=heat_score,json=heatScore,proto3" json:"heat_score,omitempty"`
	SlowQueryCount int64                  `protobuf:"varint,3,opt,name=slow_query_count,json=slowQueryCount,proto3" json:"slow_query_count,omitempty"`
	TotalQueryTime float64                `protobuf:"fixed64,4,opt,name=total_query_time,json=totalQueryTime,proto3" json:"total_query_time,omitempty"`
	TotalLockTime  float64                `protobuf:"fixed64,5,opt,name=total_lock_time,json=totalLockTime,proto3" json:"total_lock_time,omitempty"`
	AffectedFields []string               `protobuf:"bytes,6,rep,name=affected_fields,json=affectedFields,proto3" json:"affected_fields,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TableHeat) Reset() {
	*x = TableHeat{}
	mi := &file_slowquery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableHeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableHeat) ProtoMessage() {}

func (x *TableHeat) ProtoReflect() protoreflect.Message {
	mi := &file_slowquery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableHeat.ProtoReflect.Descriptor instead.
func (*TableHeat) Descriptor() ([]byte, []int) {
	return file_slowquery_proto_rawDescGZIP(), []int{3}
}

func (x *TableHeat) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *TableHeat) GetHeatScore() float64 {
	if x != nil {
		return x.HeatScore
	}
	return 0
}

func (x *TableHeat) GetSlowQueryCount() int64 {
	if x != nil {
		return x.SlowQueryCount
	}
	return 0
}

func (x *TableHeat) GetTotalQueryTime() float64 {
	if x != nil {
		return x.TotalQueryTime
	}
	return 0
}

func (x *TableHeat) GetTotalLockTime() float64 {
	if x != nil {
		return x.TotalLockTime
	}
	return 0
}

func (x *TableHeat) GetAffectedFields() []string {
	if x != nil {
		return x.AffectedFields
	}
	return nil
}

type HeatQueryResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Tables           []*TableHeat           `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	StartTime        string                 `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime          string                 `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	TotalSlowQueries int32                  `protobuf:"varint,4,opt,name=total_slow_queries,json=totalSlowQueries,proto3" json:"total_slow_queries,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeatQueryResponse) Reset() {
	*x = HeatQueryResponse{}
	mi := &file_slowquery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeatQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeatQueryResponse) ProtoMessage() {}

func (x *HeatQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slowquery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeatQueryResponse.ProtoReflect.Descriptor instead.
func (*HeatQueryResponse) Descriptor() ([]byte, []int) {
	return file_slowquery_proto_rawDescGZIP(), []int{4}
}

func (x *HeatQueryResponse) GetTables() []*TableHeat {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *HeatQueryResponse) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *HeatQueryResponse) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *HeatQueryResponse) GetTotalSlowQueries() int32 {
	if x != nil {
		return x.TotalSlowQueries
	}
	return 0
}

var File_slowquery_proto protoreflect.FileDescriptor

const file_slowquery_proto_rawDesc = "" +
	"\n" +
	"\x0fslowquery.proto\x12\tslowquery\"\xc1\x02\n" +
	"\fSlowLogEntry\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x19\n" +
	"\braw_line\x18\x02 \x01(\tR\arawLine\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12\x1d\n" +
	"\n" +
	"query_time\x18\x04 \x01(\x01R\tqueryTime\x12\x1b\n" +
	"\tlock_time\x18\x05 \x01(\x01R\blockTime\x12\x1b\n" +
	"\trows_sent\x18\x06 \x01(\x03R\browsSent\x12#\n" +
	"\rrows_examined\x18\a \x01(\x03R\frowsExamined\x12\x10\n" +
	"\x03sql\x18\b \x01(\tR\x03sql\x12\x1a\n" +
	"\bdatabase\x18\t \x01(\tR\bdatabase\x12\x12\n" +
	"\x04uuid\x18\n" +
	" \x01(\tR\x04uuid\x12\x1d\n" +
	"\n" +
	"log_offset\x18\v \x01(\x03R\tlogOffset\"~\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x05R\bsequence\x12\x12\n" +
	"\x04uuid\x18\x04 \x01(\tR\x04uuid\x12\x1d\n" +
	"\n" +
	"log_offset\x18\x05 \x01(\x03R\tlogOffset\"a\n" +
	"\x10HeatQueryRequest\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\tR\aendTime\x12\x13\n" +
	"\x05top_n\x18\x03 \x01(\x05R\x04topN\"\xee\x01\n" +
	"\tTableHeat\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x1d\n" +
	"\n" +
	"heat_score\x18\x02 \x01(\x01R\theatScore\x12(\n" +
	"\x10slow_query_count\x18\x03 \x01(\x03R\x0eslowQueryCount\x12(\n" +
	"\x10total_query_time\x18\x04 \x01(\x01R\x0etotalQueryTime\x12&\n" +
	"\x0ftotal_lock_time\x18\x05 \x01(\x01R\rtotalLockTime\x12'\n" +
	"\x0faffected_fields\x18\x06 \x03(\tR\x0eaffectedFields\"\xa9\x01\n" +
	"\x11HeatQueryResponse\x12,\n" +
	"\x06tables\x18\x01 \x03(\v2\x14.slowquery.TableHeatR\x06tables\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\tR\aendTime\x12,\n" +
	"\x12total_slow_queries\x18\x04 \x01(\x05R\x10totalSlowQueries2P\n" +
	"\x10SlowQueryService\x12<\n" +
	"\rStreamSlowLog\x12\x17.slowquery.SlowLogEntry\x1a\x0e.slowquery.Ack(\x010\x01B2Z0github.com/trae3/slowquery-lineage/pkg/slowqueryb\x06proto3"

var (
	file_slowquery_proto_rawDescOnce sync.Once
	file_slowquery_proto_rawDescData []byte
)

func file_slowquery_proto_rawDescGZIP() []byte {
	file_slowquery_proto_rawDescOnce.Do(func() {
		file_slowquery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_slowquery_proto_rawDesc), len(file_slowquery_proto_rawDesc)))
	})
	return file_slowquery_proto_rawDescData
}

var file_slowquery_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_slowquery_proto_goTypes = []any{
	(*SlowLogEntry)(nil),      // 0: slowquery.SlowLogEntry
	(*Ack)(nil),               // 1: slowquery.Ack
	(*HeatQueryRequest)(nil),  // 2: slowquery.HeatQueryRequest
	(*TableHeat)(nil),         // 3: slowquery.TableHeat
	(*HeatQueryResponse)(nil), // 4: slowquery.HeatQueryResponse
}
var file_slowquery_proto_depIdxs = []int32{
	3, // 0: slowquery.HeatQueryResponse.tables:type_name -> slowquery.TableHeat
	0, // 1: slowquery.SlowQueryService.StreamSlowLog:input_type -> slowquery.SlowLogEntry
	1, // 2: slowquery.SlowQueryService.StreamSlowLog:output_type -> slowquery.Ack
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_slowquery_proto_init() }
func file_slowquery_proto_init() {
	if File_slowquery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_slowquery_proto_rawDesc), len(file_slowquery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_slowquery_proto_goTypes,
		DependencyIndexes: file_slowquery_proto_depIdxs,
		MessageInfos:      file_slowquery_proto_msgTypes,
	}.Build()
	File_slowquery_proto = out.File
	file_slowquery_proto_goTypes = nil
	file_slowquery_proto_depIdxs = nil
}
