// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.28.3
// source: slowquery.proto

package slowquery

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	SlowQueryService_StreamSlowLog_FullMethodName = "/slowquery.SlowQueryService/StreamSlowLog"
)

// SlowQueryServiceClient is the client API for SlowQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SlowQueryServiceClient interface {
	StreamSlowLog(ctx context.Context, opts ...grpc.CallOption) (SlowQueryService_StreamSlowLogClient, error)
}

type slowQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSlowQueryServiceClient(cc grpc.ClientConnInterface) SlowQueryServiceClient {
	return &slowQueryServiceClient{cc}
}

func (c *slowQueryServiceClient) StreamSlowLog(ctx context.Context, opts ...grpc.CallOption) (SlowQueryService_StreamSlowLogClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SlowQueryService_ServiceDesc.Streams[0], SlowQueryService_StreamSlowLog_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &slowQueryServiceStreamSlowLogClient{ClientStream: stream}
	return x, nil
}

type SlowQueryService_StreamSlowLogClient interface {
	Send(*SlowLogEntry) error
	Recv() (*Ack, error)
	grpc.ClientStream
}

type slowQueryServiceStreamSlowLogClient struct {
	grpc.ClientStream
}

func (x *slowQueryServiceStreamSlowLogClient) Send(m *SlowLogEntry) error {
	return x.ClientStream.SendMsg(m)
}

func (x *slowQueryServiceStreamSlowLogClient) Recv() (*Ack, error) {
	m := new(Ack)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SlowQueryServiceServer is the server API for SlowQueryService service.
// All implementations must embed UnimplementedSlowQueryServiceServer
// for forward compatibility
type SlowQueryServiceServer interface {
	StreamSlowLog(SlowQueryService_StreamSlowLogServer) error
	mustEmbedUnimplementedSlowQueryServiceServer()
}

// UnimplementedSlowQueryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSlowQueryServiceServer struct {
}

func (UnimplementedSlowQueryServiceServer) StreamSlowLog(SlowQueryService_StreamSlowLogServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamSlowLog not implemented")
}
func (UnimplementedSlowQueryServiceServer) mustEmbedUnimplementedSlowQueryServiceServer() {}

// UnsafeSlowQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SlowQueryServiceServer will
// result in compilation errors.
type UnsafeSlowQueryServiceServer interface {
	mustEmbedUnimplementedSlowQueryServiceServer()
}

func RegisterSlowQueryServiceServer(s grpc.ServiceRegistrar, srv SlowQueryServiceServer) {
	s.RegisterService(&SlowQueryService_ServiceDesc, srv)
}

func _SlowQueryService_StreamSlowLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SlowQueryServiceServer).StreamSlowLog(&slowQueryServiceStreamSlowLogServer{ServerStream: stream})
}

type SlowQueryService_StreamSlowLogServer interface {
	Send(*Ack) error
	Recv() (*SlowLogEntry, error)
	grpc.ServerStream
}

type slowQueryServiceStreamSlowLogServer struct {
	grpc.ServerStream
}

func (x *slowQueryServiceStreamSlowLogServer) Send(m *Ack) error {
	return x.ServerStream.SendMsg(m)
}

func (x *slowQueryServiceStreamSlowLogServer) Recv() (*SlowLogEntry, error) {
	m := new(SlowLogEntry)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SlowQueryService_ServiceDesc is the grpc.ServiceDesc for SlowQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SlowQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "slowquery.SlowQueryService",
	HandlerType: (*SlowQueryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSlowLog",
			Handler:       _SlowQueryService_StreamSlowLog_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "slowquery.proto",
}
